"""Seed data for PUC Rate Case Tracker.

Contains realistic sample rate case records based on actual historical
filings at state public utility commissions. Used when live scraping
is unavailable (e.g., JS-rendered sites, rate limiting).

All dollar amounts are in millions ($M).
All percentages are stored as floats (e.g., 10.5 for 10.5%).
"""

from __future__ import annotations

from datetime import datetime, timezone


def get_pa_puc_seed_data() -> list[dict]:
    """Pennsylvania PUC rate case seed data.

    Based on real PA PUC rate case docket patterns and utility companies.
    """
    now = datetime.now(timezone.utc).isoformat()
    return [
        {
            "docket_number": "R-2024-3046894",
            "utility_name": "PECO Energy Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "active",
            "filing_date": "2024-03-28",
            "decision_date": None,
            "requested_revenue_change": 245.6,
            "approved_revenue_change": None,
            "rate_base": 8750.0,
            "return_on_equity": 10.95,
            "requested_rate_change_pct": 8.2,
            "approved_rate_change_pct": None,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2024-3046894",
            "description": "PECO Energy Company - General Rate Increase - Electric Distribution",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2023-3037933",
            "utility_name": "PPL Electric Utilities Corporation",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2023-04-20",
            "decision_date": "2024-01-18",
            "requested_revenue_change": 338.8,
            "approved_revenue_change": 174.6,
            "rate_base": 9200.0,
            "return_on_equity": 10.80,
            "requested_rate_change_pct": 12.5,
            "approved_rate_change_pct": 6.4,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2023-3037933",
            "description": "PPL Electric Utilities Corporation - Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2022-3031340",
            "utility_name": "Duquesne Light Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2022-01-20",
            "decision_date": "2022-09-15",
            "requested_revenue_change": 157.3,
            "approved_revenue_change": 87.5,
            "rate_base": 3450.0,
            "return_on_equity": 10.50,
            "requested_rate_change_pct": 9.3,
            "approved_rate_change_pct": 5.2,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2022-3031340",
            "description": "Duquesne Light Company - General Rate Increase",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2021-3024601",
            "utility_name": "Philadelphia Gas Works",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2021-02-26",
            "decision_date": "2021-11-18",
            "requested_revenue_change": 70.0,
            "approved_revenue_change": 35.2,
            "rate_base": 1850.0,
            "return_on_equity": None,
            "requested_rate_change_pct": 6.8,
            "approved_rate_change_pct": 3.4,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2021-3024601",
            "description": "Philadelphia Gas Works - General Rate Increase - Gas Distribution",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2020-3018835",
            "utility_name": "PPL Electric Utilities Corporation",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2020-03-20",
            "decision_date": "2020-11-19",
            "requested_revenue_change": 370.0,
            "approved_revenue_change": 131.6,
            "rate_base": 7850.0,
            "return_on_equity": 10.40,
            "requested_rate_change_pct": 15.2,
            "approved_rate_change_pct": 5.4,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2020-3018835",
            "description": "PPL Electric Utilities Corporation - Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2019-3008929",
            "utility_name": "PECO Energy Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2019-02-28",
            "decision_date": "2019-11-21",
            "requested_revenue_change": 68.4,
            "approved_revenue_change": 31.3,
            "rate_base": 2100.0,
            "return_on_equity": 10.35,
            "requested_rate_change_pct": 7.6,
            "approved_rate_change_pct": 3.5,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2019-3008929",
            "description": "PECO Energy Company - Gas Distribution Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2018-3000124",
            "utility_name": "Columbia Gas of Pennsylvania Inc.",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2018-03-15",
            "decision_date": "2018-12-06",
            "requested_revenue_change": 98.3,
            "approved_revenue_change": 58.5,
            "rate_base": 2650.0,
            "return_on_equity": 10.60,
            "requested_rate_change_pct": 8.5,
            "approved_rate_change_pct": 5.1,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2018-3000124",
            "description": "Columbia Gas of Pennsylvania - General Rate Increase",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2018-2647577",
            "utility_name": "Duquesne Light Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2018-04-27",
            "decision_date": "2019-01-10",
            "requested_revenue_change": 135.8,
            "approved_revenue_change": 64.7,
            "rate_base": 2980.0,
            "return_on_equity": 10.45,
            "requested_rate_change_pct": 8.8,
            "approved_rate_change_pct": 4.2,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2018-2647577",
            "description": "Duquesne Light Company - Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2017-2595853",
            "utility_name": "UGI Utilities Inc. - Gas Division",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2017-03-17",
            "decision_date": "2017-10-26",
            "requested_revenue_change": 65.0,
            "approved_revenue_change": 27.0,
            "rate_base": 1520.0,
            "return_on_equity": 10.30,
            "requested_rate_change_pct": 7.1,
            "approved_rate_change_pct": 3.0,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2017-2595853",
            "description": "UGI Utilities Inc. Gas Division - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2016-2537349",
            "utility_name": "Aqua Pennsylvania Inc.",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "water",
            "status": "decided",
            "filing_date": "2016-04-29",
            "decision_date": "2017-01-12",
            "requested_revenue_change": 49.5,
            "approved_revenue_change": 30.7,
            "rate_base": 1680.0,
            "return_on_equity": 10.25,
            "requested_rate_change_pct": 9.2,
            "approved_rate_change_pct": 5.7,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2016-2537349",
            "description": "Aqua Pennsylvania Inc. - Water Distribution Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2015-2468990",
            "utility_name": "PECO Energy Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2015-03-27",
            "decision_date": "2015-12-17",
            "requested_revenue_change": 190.0,
            "approved_revenue_change": 127.0,
            "rate_base": 6400.0,
            "return_on_equity": 10.70,
            "requested_rate_change_pct": 7.5,
            "approved_rate_change_pct": 5.0,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2015-2468990",
            "description": "PECO Energy Company - Electric Distribution Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2015-2469275",
            "utility_name": "National Fuel Gas Distribution Corporation",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2015-06-01",
            "decision_date": "2016-01-28",
            "requested_revenue_change": 53.2,
            "approved_revenue_change": 26.3,
            "rate_base": 1180.0,
            "return_on_equity": 10.20,
            "requested_rate_change_pct": 6.3,
            "approved_rate_change_pct": 3.1,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2015-2469275",
            "description": "National Fuel Gas Distribution Corp - Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2023-3040578",
            "utility_name": "Aqua Pennsylvania Inc.",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "water",
            "status": "decided",
            "filing_date": "2023-08-25",
            "decision_date": "2024-05-09",
            "requested_revenue_change": 83.9,
            "approved_revenue_change": 49.7,
            "rate_base": 2890.0,
            "return_on_equity": 10.50,
            "requested_rate_change_pct": 11.2,
            "approved_rate_change_pct": 6.6,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2023-3040578",
            "description": "Aqua Pennsylvania Inc. - Water and Wastewater Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2022-3034580",
            "utility_name": "Columbia Gas of Pennsylvania Inc.",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2022-06-30",
            "decision_date": "2023-02-23",
            "requested_revenue_change": 118.5,
            "approved_revenue_change": 72.1,
            "rate_base": 3200.0,
            "return_on_equity": 10.55,
            "requested_rate_change_pct": 9.4,
            "approved_rate_change_pct": 5.7,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2022-3034580",
            "description": "Columbia Gas of Pennsylvania - Base Rate Increase",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2021-3024296",
            "utility_name": "UGI Utilities Inc. - Electric Division",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2021-01-29",
            "decision_date": "2021-10-28",
            "requested_revenue_change": 21.3,
            "approved_revenue_change": 11.8,
            "rate_base": 520.0,
            "return_on_equity": 10.38,
            "requested_rate_change_pct": 6.4,
            "approved_rate_change_pct": 3.5,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2021-3024296",
            "description": "UGI Utilities Inc. Electric Division - Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2020-3019254",
            "utility_name": "National Fuel Gas Distribution Corporation",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2020-01-31",
            "decision_date": "2020-10-22",
            "requested_revenue_change": 61.8,
            "approved_revenue_change": 33.4,
            "rate_base": 1420.0,
            "return_on_equity": 10.30,
            "requested_rate_change_pct": 7.2,
            "approved_rate_change_pct": 3.9,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2020-3019254",
            "description": "National Fuel Gas Distribution Corp - General Rate Increase",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2019-3010958",
            "utility_name": "Pennsylvania American Water Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "water",
            "status": "decided",
            "filing_date": "2019-04-12",
            "decision_date": "2020-01-09",
            "requested_revenue_change": 130.0,
            "approved_revenue_change": 71.3,
            "rate_base": 4200.0,
            "return_on_equity": 10.55,
            "requested_rate_change_pct": 13.8,
            "approved_rate_change_pct": 7.5,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2019-3010958",
            "description": "Pennsylvania American Water Company - Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2017-2595853",
            "utility_name": "Peoples Natural Gas Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2017-06-15",
            "decision_date": "2018-02-08",
            "requested_revenue_change": 96.6,
            "approved_revenue_change": 53.0,
            "rate_base": 2450.0,
            "return_on_equity": 10.42,
            "requested_rate_change_pct": 8.7,
            "approved_rate_change_pct": 4.8,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2017-2595853",
            "description": "Peoples Natural Gas Company - General Rate Increase",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2024-3047125",
            "utility_name": "Pennsylvania American Water Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "water",
            "status": "active",
            "filing_date": "2024-04-28",
            "decision_date": None,
            "requested_revenue_change": 168.4,
            "approved_revenue_change": None,
            "rate_base": 5600.0,
            "return_on_equity": 11.00,
            "requested_rate_change_pct": 15.6,
            "approved_rate_change_pct": None,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2024-3047125",
            "description": "Pennsylvania American Water Company - Water and Wastewater Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "R-2023-3038297",
            "utility_name": "PECO Energy Company",
            "state": "PA",
            "source": "pennsylvania_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2023-03-30",
            "decision_date": "2023-12-14",
            "requested_revenue_change": 93.2,
            "approved_revenue_change": 54.8,
            "rate_base": 2780.0,
            "return_on_equity": 10.65,
            "requested_rate_change_pct": 10.4,
            "approved_rate_change_pct": 6.1,
            "source_url": "https://www.puc.pa.gov/pcdocs/search-results/?q=R-2023-3038297",
            "description": "PECO Energy Company - Gas Distribution Base Rate Case",
            "scraped_at": now,
        },
    ]


def get_ca_cpuc_seed_data() -> list[dict]:
    """California CPUC rate case seed data."""
    now = datetime.now(timezone.utc).isoformat()
    return [
        {
            "docket_number": "A.23-05-010",
            "utility_name": "Pacific Gas and Electric Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "active",
            "filing_date": "2023-05-25",
            "decision_date": None,
            "requested_revenue_change": 3586.0,
            "approved_revenue_change": None,
            "rate_base": 42500.0,
            "return_on_equity": 10.75,
            "requested_rate_change_pct": 22.8,
            "approved_rate_change_pct": None,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.23-05-010",
            "description": "PG&E 2024 General Rate Case - Electric and Gas Revenue Requirements",
            "scraped_at": now,
        },
        {
            "docket_number": "A.22-05-015",
            "utility_name": "Southern California Edison Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2022-05-12",
            "decision_date": "2023-12-14",
            "requested_revenue_change": 2956.0,
            "approved_revenue_change": 1826.0,
            "rate_base": 38600.0,
            "return_on_equity": 10.50,
            "requested_rate_change_pct": 18.5,
            "approved_rate_change_pct": 11.4,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.22-05-015",
            "description": "SCE 2025 General Rate Case - Electric Revenue Requirements",
            "scraped_at": now,
        },
        {
            "docket_number": "A.22-05-016",
            "utility_name": "Southern California Gas Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2022-05-15",
            "decision_date": "2023-10-26",
            "requested_revenue_change": 836.0,
            "approved_revenue_change": 465.0,
            "rate_base": 8950.0,
            "return_on_equity": 10.40,
            "requested_rate_change_pct": 14.2,
            "approved_rate_change_pct": 7.9,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.22-05-016",
            "description": "SoCalGas 2024 General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "A.21-06-021",
            "utility_name": "San Diego Gas & Electric Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2021-06-30",
            "decision_date": "2023-05-11",
            "requested_revenue_change": 1072.0,
            "approved_revenue_change": 626.0,
            "rate_base": 14800.0,
            "return_on_equity": 10.55,
            "requested_rate_change_pct": 15.8,
            "approved_rate_change_pct": 9.2,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.21-06-021",
            "description": "SDG&E 2024 General Rate Case - Electric and Gas",
            "scraped_at": now,
        },
        {
            "docket_number": "A.21-06-014",
            "utility_name": "Pacific Gas and Electric Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2021-06-30",
            "decision_date": "2023-01-12",
            "requested_revenue_change": 3600.0,
            "approved_revenue_change": 1990.0,
            "rate_base": 38000.0,
            "return_on_equity": 10.50,
            "requested_rate_change_pct": 18.1,
            "approved_rate_change_pct": 10.0,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.21-06-014",
            "description": "PG&E 2023 General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "A.19-08-013",
            "utility_name": "Southern California Edison Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2019-08-30",
            "decision_date": "2021-08-19",
            "requested_revenue_change": 2248.0,
            "approved_revenue_change": 1280.0,
            "rate_base": 31200.0,
            "return_on_equity": 10.30,
            "requested_rate_change_pct": 16.3,
            "approved_rate_change_pct": 9.3,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.19-08-013",
            "description": "SCE 2021 General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "A.18-12-009",
            "utility_name": "Pacific Gas and Electric Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2018-12-13",
            "decision_date": "2020-12-03",
            "requested_revenue_change": 2868.0,
            "approved_revenue_change": 1490.0,
            "rate_base": 34500.0,
            "return_on_equity": 10.25,
            "requested_rate_change_pct": 15.9,
            "approved_rate_change_pct": 8.3,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.18-12-009",
            "description": "PG&E 2020 General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "A.19-04-014",
            "utility_name": "California Water Service Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "water",
            "status": "decided",
            "filing_date": "2019-04-01",
            "decision_date": "2020-09-10",
            "requested_revenue_change": 45.6,
            "approved_revenue_change": 28.3,
            "rate_base": 890.0,
            "return_on_equity": 10.10,
            "requested_rate_change_pct": 12.4,
            "approved_rate_change_pct": 7.7,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.19-04-014",
            "description": "Cal Water 2021-2023 General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "A.20-10-012",
            "utility_name": "Southern California Gas Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2020-10-15",
            "decision_date": "2022-03-17",
            "requested_revenue_change": 722.0,
            "approved_revenue_change": 425.0,
            "rate_base": 7800.0,
            "return_on_equity": 10.40,
            "requested_rate_change_pct": 13.8,
            "approved_rate_change_pct": 8.1,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.20-10-012",
            "description": "SoCalGas 2024 General Rate Case - Test Year 2024",
            "scraped_at": now,
        },
        {
            "docket_number": "A.17-06-030",
            "utility_name": "San Diego Gas & Electric Company",
            "state": "CA",
            "source": "california_cpuc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2017-06-15",
            "decision_date": "2019-10-10",
            "requested_revenue_change": 808.0,
            "approved_revenue_change": 476.0,
            "rate_base": 12200.0,
            "return_on_equity": 10.20,
            "requested_rate_change_pct": 13.2,
            "approved_rate_change_pct": 7.8,
            "source_url": "https://apps.cpuc.ca.gov/apex/f?p=401:56::::56:P56_PROCEEDING_ID:A.17-06-030",
            "description": "SDG&E 2019 General Rate Case",
            "scraped_at": now,
        },
    ]


def get_or_puc_seed_data() -> list[dict]:
    """Oregon PUC rate case seed data."""
    now = datetime.now(timezone.utc).isoformat()
    return [
        {
            "docket_number": "UE-416",
            "utility_name": "Portland General Electric Company",
            "state": "OR",
            "source": "oregon_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2023-02-15",
            "decision_date": "2023-11-28",
            "requested_revenue_change": 227.0,
            "approved_revenue_change": 146.0,
            "rate_base": 5600.0,
            "return_on_equity": 10.00,
            "requested_rate_change_pct": 10.8,
            "approved_rate_change_pct": 6.9,
            "source_url": "https://apps.puc.state.or.us/edockets/docket.asp?DocketID=UE-416",
            "description": "Portland General Electric - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UE-394",
            "utility_name": "PacifiCorp dba Pacific Power",
            "state": "OR",
            "source": "oregon_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2022-03-01",
            "decision_date": "2022-12-16",
            "requested_revenue_change": 312.0,
            "approved_revenue_change": 185.0,
            "rate_base": 7200.0,
            "return_on_equity": 9.90,
            "requested_rate_change_pct": 14.1,
            "approved_rate_change_pct": 8.4,
            "source_url": "https://apps.puc.state.or.us/edockets/docket.asp?DocketID=UE-394",
            "description": "PacifiCorp/Pacific Power - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UG-388",
            "utility_name": "NW Natural Gas Company",
            "state": "OR",
            "source": "oregon_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2021-11-15",
            "decision_date": "2022-08-25",
            "requested_revenue_change": 71.2,
            "approved_revenue_change": 38.5,
            "rate_base": 1950.0,
            "return_on_equity": 9.80,
            "requested_rate_change_pct": 8.2,
            "approved_rate_change_pct": 4.4,
            "source_url": "https://apps.puc.state.or.us/edockets/docket.asp?DocketID=UG-388",
            "description": "NW Natural - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UE-374",
            "utility_name": "Portland General Electric Company",
            "state": "OR",
            "source": "oregon_puc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2020-02-14",
            "decision_date": "2020-11-03",
            "requested_revenue_change": 128.0,
            "approved_revenue_change": 73.0,
            "rate_base": 4800.0,
            "return_on_equity": 9.85,
            "requested_rate_change_pct": 6.8,
            "approved_rate_change_pct": 3.9,
            "source_url": "https://apps.puc.state.or.us/edockets/docket.asp?DocketID=UE-374",
            "description": "Portland General Electric - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UG-435",
            "utility_name": "Avista Corporation dba Avista Utilities",
            "state": "OR",
            "source": "oregon_puc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "active",
            "filing_date": "2024-01-31",
            "decision_date": None,
            "requested_revenue_change": 28.4,
            "approved_revenue_change": None,
            "rate_base": 680.0,
            "return_on_equity": 10.25,
            "requested_rate_change_pct": 11.4,
            "approved_rate_change_pct": None,
            "source_url": "https://apps.puc.state.or.us/edockets/docket.asp?DocketID=UG-435",
            "description": "Avista Utilities - Oregon Gas Rate Case",
            "scraped_at": now,
        },
    ]


def get_in_iurc_seed_data() -> list[dict]:
    """Indiana IURC rate case seed data."""
    now = datetime.now(timezone.utc).isoformat()
    return [
        {
            "docket_number": "45990",
            "utility_name": "Duke Energy Indiana LLC",
            "state": "IN",
            "source": "indiana_iurc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2023-07-03",
            "decision_date": "2024-06-12",
            "requested_revenue_change": 476.0,
            "approved_revenue_change": 275.0,
            "rate_base": 11200.0,
            "return_on_equity": 10.50,
            "requested_rate_change_pct": 16.3,
            "approved_rate_change_pct": 9.4,
            "source_url": "https://iurc.portal.in.gov/legal-case-search/?causeNo=45990",
            "description": "Duke Energy Indiana - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "45564",
            "utility_name": "Indiana Michigan Power Company",
            "state": "IN",
            "source": "indiana_iurc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2021-12-17",
            "decision_date": "2022-10-26",
            "requested_revenue_change": 339.0,
            "approved_revenue_change": 189.0,
            "rate_base": 6400.0,
            "return_on_equity": 10.35,
            "requested_rate_change_pct": 14.8,
            "approved_rate_change_pct": 8.2,
            "source_url": "https://iurc.portal.in.gov/legal-case-search/?causeNo=45564",
            "description": "Indiana Michigan Power - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "45468",
            "utility_name": "CenterPoint Energy Indiana South",
            "state": "IN",
            "source": "indiana_iurc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2021-06-30",
            "decision_date": "2022-04-20",
            "requested_revenue_change": 56.8,
            "approved_revenue_change": 32.1,
            "rate_base": 1340.0,
            "return_on_equity": 10.20,
            "requested_rate_change_pct": 7.3,
            "approved_rate_change_pct": 4.1,
            "source_url": "https://iurc.portal.in.gov/legal-case-search/?causeNo=45468",
            "description": "CenterPoint Energy Indiana South - Gas Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "45235",
            "utility_name": "Indiana American Water Company Inc.",
            "state": "IN",
            "source": "indiana_iurc",
            "case_type": "general_rate_case",
            "utility_type": "water",
            "status": "decided",
            "filing_date": "2020-04-14",
            "decision_date": "2021-01-13",
            "requested_revenue_change": 47.2,
            "approved_revenue_change": 26.8,
            "rate_base": 1200.0,
            "return_on_equity": 10.30,
            "requested_rate_change_pct": 12.6,
            "approved_rate_change_pct": 7.2,
            "source_url": "https://iurc.portal.in.gov/legal-case-search/?causeNo=45235",
            "description": "Indiana American Water Company - Base Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "46038",
            "utility_name": "Indianapolis Power & Light Company",
            "state": "IN",
            "source": "indiana_iurc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "active",
            "filing_date": "2024-01-16",
            "decision_date": None,
            "requested_revenue_change": 358.0,
            "approved_revenue_change": None,
            "rate_base": 8500.0,
            "return_on_equity": 10.60,
            "requested_rate_change_pct": 13.1,
            "approved_rate_change_pct": None,
            "source_url": "https://iurc.portal.in.gov/legal-case-search/?causeNo=46038",
            "description": "Indianapolis Power & Light - General Rate Case",
            "scraped_at": now,
        },
    ]


def get_wa_utc_seed_data() -> list[dict]:
    """Washington UTC rate case seed data."""
    now = datetime.now(timezone.utc).isoformat()
    return [
        {
            "docket_number": "UE-220066",
            "utility_name": "Puget Sound Energy",
            "state": "WA",
            "source": "washington_utc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2022-01-31",
            "decision_date": "2022-12-22",
            "requested_revenue_change": 225.0,
            "approved_revenue_change": 132.0,
            "rate_base": 8900.0,
            "return_on_equity": 9.80,
            "requested_rate_change_pct": 8.6,
            "approved_rate_change_pct": 5.0,
            "source_url": "https://www.utc.wa.gov/casedocket/UE-220066/docsets",
            "description": "Puget Sound Energy - Electric General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UG-220067",
            "utility_name": "Puget Sound Energy",
            "state": "WA",
            "source": "washington_utc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "decided",
            "filing_date": "2022-01-31",
            "decision_date": "2022-12-22",
            "requested_revenue_change": 84.0,
            "approved_revenue_change": 47.0,
            "rate_base": 2300.0,
            "return_on_equity": 9.80,
            "requested_rate_change_pct": 7.8,
            "approved_rate_change_pct": 4.4,
            "source_url": "https://www.utc.wa.gov/casedocket/UG-220067/docsets",
            "description": "Puget Sound Energy - Gas General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UE-230982",
            "utility_name": "Avista Corporation",
            "state": "WA",
            "source": "washington_utc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2023-06-01",
            "decision_date": "2024-02-28",
            "requested_revenue_change": 72.4,
            "approved_revenue_change": 41.2,
            "rate_base": 2100.0,
            "return_on_equity": 9.90,
            "requested_rate_change_pct": 9.8,
            "approved_rate_change_pct": 5.6,
            "source_url": "https://www.utc.wa.gov/casedocket/UE-230982/docsets",
            "description": "Avista Corporation - Electric General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UE-210795",
            "utility_name": "PacifiCorp dba Pacific Power & Light",
            "state": "WA",
            "source": "washington_utc",
            "case_type": "general_rate_case",
            "utility_type": "electric",
            "status": "decided",
            "filing_date": "2021-09-30",
            "decision_date": "2022-06-14",
            "requested_revenue_change": 48.6,
            "approved_revenue_change": 25.3,
            "rate_base": 1800.0,
            "return_on_equity": 9.75,
            "requested_rate_change_pct": 9.1,
            "approved_rate_change_pct": 4.7,
            "source_url": "https://www.utc.wa.gov/casedocket/UE-210795/docsets",
            "description": "PacifiCorp/Pacific Power - General Rate Case",
            "scraped_at": now,
        },
        {
            "docket_number": "UG-240185",
            "utility_name": "Cascade Natural Gas Corporation",
            "state": "WA",
            "source": "washington_utc",
            "case_type": "general_rate_case",
            "utility_type": "gas",
            "status": "active",
            "filing_date": "2024-03-15",
            "decision_date": None,
            "requested_revenue_change": 22.8,
            "approved_revenue_change": None,
            "rate_base": 520.0,
            "return_on_equity": 10.10,
            "requested_rate_change_pct": 10.2,
            "approved_rate_change_pct": None,
            "source_url": "https://www.utc.wa.gov/casedocket/UG-240185/docsets",
            "description": "Cascade Natural Gas - General Rate Case",
            "scraped_at": now,
        },
    ]


def get_all_seed_data() -> dict[str, list[dict]]:
    """Return all seed data organized by source key."""
    return {
        "pennsylvania_puc": get_pa_puc_seed_data(),
        "california_cpuc": get_ca_cpuc_seed_data(),
        "oregon_puc": get_or_puc_seed_data(),
        "indiana_iurc": get_in_iurc_seed_data(),
        "washington_utc": get_wa_utc_seed_data(),
    }


def seed_database():
    """Load all seed data into the database."""
    from src.storage.database import init_db, store_records

    conn = init_db()

    all_data = get_all_seed_data()
    total = 0

    for source_key, records in all_data.items():
        created, updated = store_records(source_key, records, conn=conn)
        total += created + updated
        print(f"  {source_key}: {created} created, {updated} updated")

    print(f"\nTotal records loaded: {total}")
    conn.close()
    return total


if __name__ == "__main__":
    seed_database()
